side-peek/sidepeek_backend

- .github/CODEOWNERS
> 자동 PR 리뷰어 설정

- .gitignore
- .gitmodules
- src/main/resources/application-local.yml
- src/test/resources/application.yml
Resolves #21 
```
// in 프로젝트 폴더
git pull
git submodule update --init --update
```
```
// 서브모듈 폴더(./sidepeek_backend_secret)로 이동 후
git pull
```
> 민감 정보 관리를 위한 서브모듈 도입

- src/main/java/sixgaezzang/sidepeek/users/domain/User.java
> User 클래스에서 Provider 필드 @Enumerated(EnumType.STRING) 설정

- .github/workflows/ci.yml
- .gitignore
- .gitmodules
- src/test/resources/application.yml
Resolves #3 #9 #17 
- GitHub Action 관련 블로깅 및 트러블 슈팅 기록은 [GitHub Actions로 CI 파이프라인 구축하기](https://www.notion.so/prgrms/GitHub-Actions-CI-04e67554b9f5474fae9f28a2ab093b0a?pvs=4) 글을 참고해주세요!
- PR 올리면서 Jacoco 커버리지 설정이나 Slack 알림이 괜찮은지 확인 부탁드립니다! 수정할 부분이 있다면, 편하게 말씀해주세요! 👍
> GitHub Action 이용한 CI 파이프라인 구축

- .github/workflows/ci.yml
Resolves #60 
- [참고자료](https://github.com/Madrapps/jacoco-report/issues/66)
- 요기 보니 버전 업그레이드 하면 해결 된다고 해서 업그레이드 했습니다!
> jacoco-report@v1.6 버전업!

- src/main/java/sixgaezzang/sidepeek/auth/jwt/JWTValidationFilter.java
- src/main/java/sixgaezzang/sidepeek/common/annotation/Login.java
- src/main/java/sixgaezzang/sidepeek/common/exception/GlobalExceptionHandler.java
- src/main/java/sixgaezzang/sidepeek/common/exception/InvalidAuthenticationException.java
- src/main/java/sixgaezzang/sidepeek/common/resolver/LoginUserArgumentResolver.java
- src/main/java/sixgaezzang/sidepeek/config/SecurityConfig.java
- src/main/java/sixgaezzang/sidepeek/config/WebConfig.java
- src/main/resources/db/data/afterMigrate.sql
Resolves #63 
- `@Login` 애너테이션 사용 방법은 대면으로 말씀드리도록 하겠습니다:)
> JWT 검증 로직 구현

- src/main/java/sixgaezzang/sidepeek/auth/controller/AuthController.java
- src/main/java/sixgaezzang/sidepeek/auth/dto/request/ReissueTokenRequest.java
- src/main/java/sixgaezzang/sidepeek/auth/service/AuthService.java
- src/main/java/sixgaezzang/sidepeek/auth/service/RefreshTokenService.java
- src/main/java/sixgaezzang/sidepeek/common/resolver/LoginUserArgumentResolver.java
- src/test/java/sixgaezzang/sidepeek/auth/service/AuthServiceTest.java
- src/test/java/sixgaezzang/sidepeek/auth/service/RefreshTokenServiceTest.java
Resolves #66 
- AuthServiceTest에 TODO로 작성된 부분은 추후 테스트 코드 추가하도록 해겠습니다! (시간과 관련된 테스트라 모킹하기가 어렵더라구요.. 조금 더 공부해보고 추가하겠습니다!)
> Refresh / Access Token 재발급 기능 구현

- .github/workflows/ci.yml
- [Redis Server in GitHub Actions](https://github.com/marketplace/actions/redis-server-in-github-actions#usage)를 마켓 플레이스에서 찾아서 설정해서 원하는 포트로 매핑할 수 있도록 해결!
- 저도 정확한 문제 상황은 모르겠지만 제가 찾아본 바로는 [스택오버 플로우 질문 답변](https://stackoverflow.com/questions/64126095/github-action-use-environment-variable-as-port)에 따르면 현재 redis 설정하고 있는 부분이 secrets 환경 변수가 인식이 안되는 부분이라고 합니다! 저희가 하려고 하는 아래 설정은 불가능 하다고 합니다... 😭그래서  현재 db 설정한 것처럼 따로 job으로 돌려야할 것 같네요..!
> 깃허브 액션 에러 해결 테스트

- src/main/java/sixgaezzang/sidepeek/config/properties/S3Properties.java
- src/main/java/sixgaezzang/sidepeek/media/service/MediaService.java
- src/main/java/sixgaezzang/sidepeek/media/util/MediaConstant.java
> 이미지 저장 경로 수정

- src/main/java/sixgaezzang/sidepeek/auth/dto/request/LoginRequest.java
- src/main/java/sixgaezzang/sidepeek/common/dto/response/Page.java
- src/main/java/sixgaezzang/sidepeek/users/controller/UserController.java
- src/main/resources/db/data/afterMigrate.sql
> Dev Server afterMigration 적용 및 더미 데이터 추가

- src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java
Resolves #165 
- 추가 기능 구현은 없고, 프로젝트 수정 후에 프로젝트 상세 조회처럼 응답에 댓글, 좋아요 여부 불러왔습니다!
> 프로젝트 수정 후 댓글도 불러오도록 수정

- src/main/java/sixgaezzang/sidepeek/auth/domain/AuthProvider.java
- src/main/java/sixgaezzang/sidepeek/auth/dto/response/SocialLoginResponse.java
- src/main/java/sixgaezzang/sidepeek/auth/oauth/service/OAuth2UserServiceImpl.java
> 소셜 로그인 시 닉네임 데이터가 있더라도 이메일 데이터가 없으면 회원가입이 완료되지 않는 오류 해결

- src/main/java/sixgaezzang/sidepeek/config/SecurityConfig.java
> cors 에러 해결를 위한 설정 추가

- src/main/java/sixgaezzang/sidepeek/common/controller/HealthCheckController.java
- src/main/java/sixgaezzang/sidepeek/config/SecurityConfig.java
CORS 에러 해결을 위해 dev -> main push
> Hotfix CORS 에러 해결

- src/main/java/sixgaezzang/sidepeek/users/util/UserConstant.java
> 회원 소개글 최대 길이 설정 DB와 서버 같도록 수정

- src/main/java/sixgaezzang/sidepeek/common/exception/GlobalExceptionHandler.java
> HttpMessageNotReadableException 예외 메시지 구체화

- src/main/java/sixgaezzang/sidepeek/projects/util/validation/ProjectValidator.java
> 프로젝트 시작 끝 기간이 같으면 안되는 오류 수정

- src/main/java/sixgaezzang/sidepeek/common/exception/GlobalExceptionHandler.java
- src/main/java/sixgaezzang/sidepeek/projects/exception/message/MemberErrorMessage.java
- src/main/java/sixgaezzang/sidepeek/projects/util/validation/MemberValidator.java
- npe가 너무 알림으로 많이와서 핸들러를 임시방편으로 구현했습니다!
- 알림은 안 오지만 sentry로 계속 확인은 해야될 것 같아요!
> NPE 핸들러 구현

- README.md
> docs: 아키텍쳐 이미지 삽입

- README.md
> Dev 브랜치 변경 반영
