build.gradle, src/main/java/sixgaezzang/sidepeek/projects/domain/ProjectSkill.java, src/main/java/sixgaezzang/sidepeek/skill/controller/SkillController.java, src/main/java/sixgaezzang/sidepeek/skill/domain/Skill.java, src/main/java/sixgaezzang/sidepeek/skill/dto/SkillResponse.java, src/main/java/sixgaezzang/sidepeek/skill/dto/SkillSearchResponse.java, src/main/java/sixgaezzang/sidepeek/skill/repository/SkillRepository.java, src/main/java/sixgaezzang/sidepeek/skill/serivce/SkillService.java, src/main/java/sixgaezzang/sidepeek/users/controller/UserController.java, src/main/java/sixgaezzang/sidepeek/users/domain/UserSkill.java, src/main/java/sixgaezzang/sidepeek/users/dto/UserSearchResponse.java, src/main/java/sixgaezzang/sidepeek/users/dto/UserSummaryResponse.java, src/main/java/sixgaezzang/sidepeek/users/repository/UserRepository.java, src/main/java/sixgaezzang/sidepeek/users/service/UserService.java
This reverts commit 61d76e021279d1e78b94a120029c28f10bb3e0b3.
Resolves #38 
Resolves #33 
Resolves #30 
- 코드 PR이 꼬여버려서 두 가지 기능을 같이 올리게 되었습니다.,. 죄송합니다.. 
- 작동하는 것도 확인하고 올립니다!
- 두 기능 구조가 비슷해서 같이 작업했는데 앞으론 하나 제대로 하고 브랜치 따로 둬서 해야겠습니다...😇
- **두 기능 모두 프로젝트 게시글 저장 페이지에서 각각 스택 검색, 회원 검색에 이용하는 api 입니다!**
- 위 상황을 고려해서 쿼리스트링을 안 보낼 때는 전체 목록이 나오게 하고 keyword(검색어)가 주어질 때는 검색어가 포함된 이름을 가진 각각의 객체들이 반환되도록 구현했습니다!
- 테스트 코드와 swagger 설정은 저도 나중에 나눠서 올리겠습니다!
=> 기술 스택 및 회원 닉네임 검색 api 구현

src/main/java/sixgaezzang/sidepeek/common/exception/ErrorResponse.java, src/main/java/sixgaezzang/sidepeek/common/exception/GlobalExceptionHandler.java, src/main/java/sixgaezzang/sidepeek/common/util/ValidationUtils.java, src/main/java/sixgaezzang/sidepeek/users/domain/Password.java, src/main/java/sixgaezzang/sidepeek/users/domain/User.java
Resolves #44 
- 회원가입 기능을 구현하다보니 기본적인 예외처리가 필요할 것 같아서 추가했습니당:)
- 저희 `ErrorCode`를 만들건지, 예외 메시지만 상수 처리(클래스 분리)할지 정한 뒤 그거에 따라 `Controller Advice`도 나중에 변경하면 될 것 같아용!
=> 컨트롤러 어드바이스 세팅

build.gradle, config/checkstyle/checkstyle.xml, src/test/java/sixgaezzang/sidepeek/users/service/UserServiceTest.java
=> 회원가입 서비스 테스트 코드 작성

src/main/java/sixgaezzang/sidepeek/skill/controller/SkillController.java, src/main/java/sixgaezzang/sidepeek/skill/domain/Skill.java, src/main/java/sixgaezzang/sidepeek/skill/dto/response/SkillResponse.java, src/main/java/sixgaezzang/sidepeek/skill/dto/response/SkillSearchResponse.java, src/main/java/sixgaezzang/sidepeek/skill/serivce/SkillService.java, src/main/java/sixgaezzang/sidepeek/users/controller/UserController.java, src/main/java/sixgaezzang/sidepeek/users/domain/User.java, src/main/java/sixgaezzang/sidepeek/users/dto/request/SignUpRequest.java, src/main/java/sixgaezzang/sidepeek/users/dto/response/UserSearchResponse.java, src/main/java/sixgaezzang/sidepeek/users/dto/response/UserSummaryResponse.java, src/main/java/sixgaezzang/sidepeek/users/service/UserService.java, src/test/java/sixgaezzang/sidepeek/skill/serivce/SkillServiceTest.java, src/test/java/sixgaezzang/sidepeek/users/service/UserServiceTest.java
Resolves #51 
- 기술 스택 및 회원 닉네임 검색 api 관련해서 마무리로 테스트 코드 작성 및 리팩토링 진행했습니다! 
- 테스트 코드 작성
- Swagger 정리하기
- 예외 처리 핸들링
- 코드,,양이 좀 많아지긴 했네요ㅠㅠㅠ 죄송합니다ㅠㅠ🥲
=> 기술 스택 및 회원 닉네임 검색 api 리팩토링 및 테스트

src/main/java/sixgaezzang/sidepeek/users/controller/UserController.java, src/main/java/sixgaezzang/sidepeek/users/domain/User.java, src/main/java/sixgaezzang/sidepeek/users/dto/request/CheckEmailRequest.java, src/main/java/sixgaezzang/sidepeek/users/dto/request/CheckNicknameRequest.java, src/main/java/sixgaezzang/sidepeek/users/dto/request/SignUpRequest.java, src/main/java/sixgaezzang/sidepeek/users/service/UserService.java, src/test/java/sixgaezzang/sidepeek/users/service/UserServiceTest.java
Resolves #54 
- 이메일 중복 검사 기능과 중복되는 부분이 많아서 일단, `feat/#50-check-email-duplicate` 브랜치에서 새로운 브랜치 따서 작업 했습니다! `feat/#50-check-email-duplicate`가 `dev`에 머지되면  `feat/#54-check-nickname-duplicate`도 dev로 머지하겠습니당!
=> 닉네임 중복 검사 기능 구현

.github/workflows/ci.yml, .gitignore, build.gradle, docker/docker-compose.yml, src/main/java/sixgaezzang/sidepeek/auth/domain/RefreshToken.java, src/main/java/sixgaezzang/sidepeek/auth/dto/response/LoginResponse.java, src/main/java/sixgaezzang/sidepeek/auth/jwt/JWTManager.java, src/main/java/sixgaezzang/sidepeek/auth/jwt/JWTValidationFilter.java, src/main/java/sixgaezzang/sidepeek/auth/repository/RefreshTokenRepository.java, src/main/java/sixgaezzang/sidepeek/auth/service/AuthService.java, src/main/java/sixgaezzang/sidepeek/auth/service/RefreshTokenService.java, src/main/java/sixgaezzang/sidepeek/common/exception/GlobalExceptionHandler.java, src/main/java/sixgaezzang/sidepeek/common/exception/TokenValidationFailException.java, src/main/java/sixgaezzang/sidepeek/config/RedisConfig.java, src/main/java/sixgaezzang/sidepeek/config/SecurityConfig.java, src/main/java/sixgaezzang/sidepeek/config/properties/JWTProperties.java, src/main/java/sixgaezzang/sidepeek/config/properties/RedisProperties.java, src/main/resources/db/migration/V1__init.sql, src/test/java/sixgaezzang/sidepeek/auth/service/AuthServiceTest.java, src/test/java/sixgaezzang/sidepeek/auth/service/RefreshTokenServiceTest.java
Fixes #12 
- Refresh Token을 RDB와 Redis 중 어떤 스토리지에 저장할지 고민한 결과 
1️⃣ Refresh Token의 접근이 빈번함 (빠른 in-memery 스토리지인 Redis가 적합)
2️⃣ DB에 영구적으로 보관되는 데이터가 아님
등의 이유로 **Redis에 저장하기로 결정**했습니다!
- 레디스 관련 `docker-compose.yml` 파일을 수정했기 때문에 `.env` 파일에도 환경 변수 설정이 필요합니다! (구두로 전달드리겠습니당!)
**🙏🏻 sidepeek_backend_secret에 Redis 관련 속성을 추가해서 pull 한번만 부탁 드립니다!**
=> 자동 로그인(리프레시 토큰) 기능 구현

src/main/java/sixgaezzang/sidepeek/auth/controller/AuthController.java, src/main/java/sixgaezzang/sidepeek/auth/service/AuthService.java, src/test/java/sixgaezzang/sidepeek/auth/service/AuthServiceTest.java
=> access token 검증 기능 구현

src/main/java/sixgaezzang/sidepeek/users/domain/Password.java, src/main/java/sixgaezzang/sidepeek/users/domain/User.java, src/main/java/sixgaezzang/sidepeek/users/exception/UserErrorCode.java, src/main/java/sixgaezzang/sidepeek/users/service/UserService.java, src/test/java/sixgaezzang/sidepeek/users/service/UserServiceTest.java
Resolves #74 
저희가 커스텀 에러를 사용하지 않는다면, 커스텀 에러 코드(ex. 1001)를 사용할 수 없을 것 같은데 
1️⃣ 커스텀 에러를 사용한다 
2️⃣ 에러 코드없이 메시지만 enum으로 관리한다 
같은 방법이 있을 것 같은데, 다음주에 이야기 해보면 좋을 것 같습니당!
=> 커스텀 에러 코드 적용(User)

src/main/java/sixgaezzang/sidepeek/projects/controller/ProjectController.java, src/main/java/sixgaezzang/sidepeek/projects/dto/request/MemberSaveRequest.java, src/main/java/sixgaezzang/sidepeek/projects/dto/request/ProjectRequest.java, src/main/java/sixgaezzang/sidepeek/projects/dto/request/ProjectSaveRequest.java, src/main/java/sixgaezzang/sidepeek/projects/dto/request/ProjectSkillSaveRequest.java, src/main/java/sixgaezzang/sidepeek/projects/dto/response/MemberSummary.java, src/main/java/sixgaezzang/sidepeek/projects/dto/response/OverviewImageSummary.java, src/main/java/sixgaezzang/sidepeek/projects/dto/response/ProjectResponse.java, src/main/java/sixgaezzang/sidepeek/projects/dto/response/ProjectSkillSummary.java, src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java, src/main/java/sixgaezzang/sidepeek/skill/dto/response/SkillResponse.java, src/main/java/sixgaezzang/sidepeek/users/dto/response/UserSummary.java, src/test/java/sixgaezzang/sidepeek/projects/service/ProjectServiceTest.java, src/test/java/sixgaezzang/sidepeek/projects/util/FakeDtoProvider.java
Resolves #77 
- 브랜치를 나눠야 했는데 확인을 못하고 푸시 했습니다,,, 양이 많지는 않아서 함께 올립니다!  
- 스웨거에 예시 값 적용해놓았습니당!
- 요청 예시 적용
- 성공 응답 예시 적용
=> 프로젝트 저장/수정/삭제 api 스웨거 적용

src/main/resources/db/data/afterMigrate.sql
Resolves #111 
- 앞 PR을 머지해야 머지할 수 있..습닏..다..! 죄송합니다!!!!!!😭
=> afterMigrate.sql 설정에 스킬 데이터 21개 추가 

src/main/java/sixgaezzang/sidepeek/common/doc/SkillControllerDoc.java, src/main/java/sixgaezzang/sidepeek/common/doc/UserControllerDoc.java, src/main/java/sixgaezzang/sidepeek/common/exception/GlobalExceptionHandler.java, src/main/java/sixgaezzang/sidepeek/skill/controller/SkillController.java, src/main/java/sixgaezzang/sidepeek/users/controller/UserController.java, src/main/java/sixgaezzang/sidepeek/users/service/UserService.java
Resolves #132 
- 인터페이스를 이용해서 컨트롤러를 구현한 경우에는 jakarta.validation 계열 어노테이션을 똑같이 붙여줘야한다. 안그러면  jakarta.validation에서 아래 예외를 발생시킨다. 
- 이상한 점은 쿼리 스트링 적용을 한 메서드에서만 일어난다는 것이다.
```
jakarta.validation.ConstraintDeclarationException: HV000151: A method overriding another method must not redefine the parameter constraint configuration, ~
```
=> 기술 스택 검색, 회원 닉네임 검색 에러 해결 #132

src/main/java/sixgaezzang/sidepeek/auth/repository/AuthProviderRepository.java, src/main/java/sixgaezzang/sidepeek/auth/service/AuthService.java, src/main/java/sixgaezzang/sidepeek/users/dto/response/UserProfileResponse.java, src/main/java/sixgaezzang/sidepeek/users/dto/response/UserSummary.java, src/main/java/sixgaezzang/sidepeek/users/exception/message/UserErrorMessage.java, src/main/java/sixgaezzang/sidepeek/users/service/UserService.java, src/test/java/sixgaezzang/sidepeek/auth/service/AuthServiceTest.java
Resolves  #142 
- 테스트 코드에는 반영을 못했습니다! 
- 브랜치가 꼬여서,,, [refactor/#130-seperate-project-save-method](https://github.com/side-peek/sidepeek_backend/tree/refactor/%23130-seperate-project-save-method)에서 브랜치를 만들어버렸습니다... 참고만 해주시면 감사하겠습니다!
=> UserSummary, UserProfileResponse에 isSocialLogin 추가

src/main/java/sixgaezzang/sidepeek/comments/dto/response/CommentWithCountResponse.java, src/main/java/sixgaezzang/sidepeek/comments/service/CommentService.java, src/main/java/sixgaezzang/sidepeek/projects/dto/response/ProjectResponse.java, src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java, src/test/java/sixgaezzang/sidepeek/projects/service/ProjectServiceTest.java
=> 프로젝트 상세 조회 시 누락된 댓글 수 및 댓글 관련 응답 객체 수정

src/main/java/sixgaezzang/sidepeek/projects/dto/request/SaveProjectRequest.java, src/main/java/sixgaezzang/sidepeek/users/domain/User.java, src/main/java/sixgaezzang/sidepeek/users/dto/response/UserProfileResponse.java, src/main/java/sixgaezzang/sidepeek/users/dto/response/UserSummary.java, src/main/resources/db/data/afterMigrate.sql
Resolves  #156 
- string: 빈 문자열(`""`)로 통일
- 배열: 빈 배열(`[]`)로 통일
- 숫자, 객체: `null`로 통일
- enum 타입: 문자열로 주고받기 때문에 string 형식과 동일하게 빈 문자열(`""`)
- 시간(ex. 프로젝트 시작, 끝 기간): `null`로 통일  
- 통일 형식에 대해 궁금하시다면 자세한 사항은 #156 참고해주시면 감사하겠습니당!
=> 옵션 값이 있는 요청, 응답에서 값이 빈 경우 타입 통일

src/main/java/sixgaezzang/sidepeek/common/doc/LikeControllerDoc.java, src/main/java/sixgaezzang/sidepeek/like/controller/LikeController.java, src/main/java/sixgaezzang/sidepeek/like/dto/response/LikeResponse.java, src/main/java/sixgaezzang/sidepeek/like/exception/message/LikeErrorMessage.java, src/main/java/sixgaezzang/sidepeek/like/repository/LikeRepository.java, src/main/java/sixgaezzang/sidepeek/like/service/LikeService.java, src/main/java/sixgaezzang/sidepeek/like/util/validation/LikeValidator.java, src/main/java/sixgaezzang/sidepeek/projects/domain/Project.java, src/main/java/sixgaezzang/sidepeek/projects/dto/request/SaveProjectRequest.java, src/main/java/sixgaezzang/sidepeek/users/domain/User.java, src/main/java/sixgaezzang/sidepeek/users/dto/response/UserProfileResponse.java, src/main/java/sixgaezzang/sidepeek/users/dto/response/UserSummary.java, src/main/resources/db/data/afterMigrate.sql, src/test/java/sixgaezzang/sidepeek/like/service/LikeServiceTest.java
=> 좋아요 토글에서 좋아요, 좋아요 취소로 엔드포인트 분리

src/main/java/sixgaezzang/sidepeek/common/doc/ProjectControllerDoc.java, src/main/java/sixgaezzang/sidepeek/common/resolver/LoginUserArgumentResolver.java, src/main/java/sixgaezzang/sidepeek/like/repository/LikeRepositoryCustom.java, src/main/java/sixgaezzang/sidepeek/like/repository/LikeRepositoryCustomImpl.java, src/main/java/sixgaezzang/sidepeek/projects/controller/ProjectController.java, src/main/java/sixgaezzang/sidepeek/projects/dto/response/ProjectResponse.java, src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java, src/main/java/sixgaezzang/sidepeek/users/service/UserService.java, src/test/java/sixgaezzang/sidepeek/projects/service/ProjectServiceTest.java
Resolves #171 
로그인한 사용자가 해당 프로젝트에 좋아요를 눌렀다면 likeId = 1, 사용자가 로그인하지 않았거나 좋아요를 누르지 않은 프로젝트라면 null을 반환합니다!
=> 프로젝트 상세 조회 시 응답에 좋아요 Id 추가

src/main/java/sixgaezzang/sidepeek/projects/domain/file/File.java, src/main/java/sixgaezzang/sidepeek/projects/domain/file/FileType.java, src/main/java/sixgaezzang/sidepeek/projects/repository/FileRepository.java, src/main/java/sixgaezzang/sidepeek/projects/service/FileService.java, src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java, src/main/resources/db/data/afterMigrate.sql, src/main/resources/db/migration/V5__delete_file_type.sql, src/test/java/sixgaezzang/sidepeek/projects/service/FileServiceTest.java
Resolves #117 
- 현재 프로젝트에서 관리하는 파일은 크게 `페이지 상단의 오버뷰 이미지`와 `기능설명/트러블 슈팅 글 안의 이미지` 두 종류인데 그 중에서 오버뷰 이미지는 따로 테이블에서 관리하고 있습니다! 
- 테이블에서 관리하는 이미지가 오버뷰 이미지만 있기 때문에 현재는 file type으로 구분하지 않아도 되어서 구조를 더 단순하게 하고자 현재 상황에 맞추어 제거했습니다!
=> 사용하지 않는 fileType 필드 제거

build.gradle, src/main/java/sixgaezzang/sidepeek/common/exception/GlobalExceptionHandler.java, src/main/java/sixgaezzang/sidepeek/media/exception/MediaExceptionHandler.java, src/main/resources/spy.properties
Resolves #175 
- 블로그 기록: [[Spring] 서버에 Sentry를 적용해보자](https://medium.com/@Hailey24/spring-dev-%EC%84%9C%EB%B2%84%EC%97%90-sentry%EB%A5%BC-%EC%A0%81%EC%9A%A9%ED%95%B4%EB%B3%B4%EC%9E%90-1-100ab28a3fa8)
- sentry가 여러명으로 팀 구성하면 유료 요금제를 내야하더라구요... 그래서 아래 두 가지 방안을 생각해보았습니다! 둘 다 저는 상관 없으니 편하게 이야기 해주세요!
- 무료 요금제로 한 명이 대표로 Sentry 관리하기
- 유료 요금제 체험판으로 2주동안 다같이 자유롭게 사용하기. 단 2주(약 13일..?)가 지나면 다시 개인 관리ㅠㅠ
- 참고로 정말 야속하게도 sentry로 직접 슬랙 연동해서 알림 보내는 것은 유료더라구요...ㅠㅠ 그래서 서버에 직접 슬랙을 연동하는 방법밖에 없어서 이 부분은 이어서 제가 찾아보도록 하겠습니다! 😭
=> dev 서버 Sentry 설정

src/main/java/sixgaezzang/sidepeek/comments/service/CommentService.java, src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java, src/test/java/sixgaezzang/sidepeek/projects/service/ProjectServiceTest.java
=> 댓글 조회시 isOwner 오류

src/main/java/sixgaezzang/sidepeek/common/annotation/Ip.java, src/main/java/sixgaezzang/sidepeek/common/doc/ProjectControllerDoc.java, src/main/java/sixgaezzang/sidepeek/common/resolver/IpArgumentResolver.java, src/main/java/sixgaezzang/sidepeek/config/RedisConfig.java, src/main/java/sixgaezzang/sidepeek/config/WebConfig.java, src/main/java/sixgaezzang/sidepeek/projects/controller/ProjectController.java, src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java, src/test/java/sixgaezzang/sidepeek/projects/service/ProjectServiceTest.java
Resolves #177 
`기존의 조회수 정책`은 프로젝트를 상세 조회할 때마다 **조회수가 무조건 증가하는 방식**으로 구현되어 있었습니다. 그러나 이 방법은 프로젝트, 댓글, 좋아요를 생성, 수정, 삭제한 후에 다시 프로젝트를 조회할 때 조회수가 다시 증가하는 문제가 발생했습니다. 
이 문제를 해결하기 위해, 회원이든 비회원이든 요청하는 IP 주소를 가져와 프로젝트 ID로 key를 만들어 **Redis**에 저장하는 방식으로 변경했습니다. 이 방식을 통해 **동일한 IP로 `당일`에 이미 조회한 상세 프로젝트라면 조회수를 증가하지 않도록** 설정했습니다.
=> 프로젝트 상세 조회 시 조회수 어뷰징 버그 해결

.gitignore, src/main/java/sixgaezzang/sidepeek/auth/oauth/service/strategy/GithubUserInfoMapper.java, src/main/java/sixgaezzang/sidepeek/auth/oauth/service/strategy/UserInfoMapperFactory.java
=> 소셜 로그인 시 닉네임이 이미 우리 서비스에 존재하는 경우 예외를 발생시키는 오류 수정

src/main/java/sixgaezzang/sidepeek/common/exception/GlobalExceptionHandler.java
Resolves #209 
- 위 사진에 띄어쓰기는 수정이 된 상태입니다!
- 해당 에러의 핸들러가 없어서 계속 슬랙 알림이 오더라구요! 그래서 핸들러를 반영했습니다!
- [405번 http status 설명](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405)에 따라서 응답 헤더에 allow method 목록도 추가해주었습니다!
=> HttpRequestMethodNotSupportedException 핸들러 구현

src/main/java/sixgaezzang/sidepeek/common/exception/GlobalExceptionHandler.java, src/main/java/sixgaezzang/sidepeek/common/util/component/SlackClient.java, src/main/java/sixgaezzang/sidepeek/media/exception/MediaExceptionHandler.java
=> Slack 메시지에 요청 url과 메서드 확인할 수 있도록 구현

src/main/java/sixgaezzang/sidepeek/projects/dto/request/FindProjectRequest.java, src/main/java/sixgaezzang/sidepeek/projects/repository/project/ProjectRepositoryCustomImpl.java
=> 프로젝트 키워드로 검색 시 기술 스택으로 필터링 가능하도록 수정

src/main/java/sixgaezzang/sidepeek/auth/exception/message/AuthErrorMessage.java, src/main/java/sixgaezzang/sidepeek/auth/filter/JWTValidationFilter.java, src/main/java/sixgaezzang/sidepeek/auth/jwt/JWTManager.java, src/main/java/sixgaezzang/sidepeek/auth/service/AuthService.java, src/main/java/sixgaezzang/sidepeek/auth/service/RefreshTokenService.java, src/main/java/sixgaezzang/sidepeek/common/exception/GlobalExceptionHandler.java, src/main/java/sixgaezzang/sidepeek/common/exception/InvalidAuthenticationException.java, src/main/java/sixgaezzang/sidepeek/common/resolver/IpArgumentResolver.java, src/main/java/sixgaezzang/sidepeek/common/resolver/LoginUserArgumentResolver.java, src/main/java/sixgaezzang/sidepeek/common/util/validation/ValidationUtils.java, src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java, src/main/java/sixgaezzang/sidepeek/users/util/validation/UserValidator.java, src/test/java/sixgaezzang/sidepeek/auth/service/RefreshTokenServiceTest.java, src/test/java/sixgaezzang/sidepeek/comments/service/CommentServiceTest.java, src/test/java/sixgaezzang/sidepeek/like/service/LikeServiceTest.java, src/test/java/sixgaezzang/sidepeek/media/service/MediaServiceTest.java, src/test/java/sixgaezzang/sidepeek/projects/service/ProjectServiceTest.java, src/test/java/sixgaezzang/sidepeek/users/service/UserServiceTest.java
Fixes #189
- 토큰 관련은 TokenValidationFailException => status code: unAuthorized 
- 인증에서 토큰 관련 말고는 BasCredentialsException => status code: unAuthorized 
- 인가(권한) 관련은 AccessDeniedException 
- 인증/인가 예외가 통일되면 더 좋을 것 같아서 조금 리팩토링해봤는데 어떠신지 여쭤봅니당!! 
- GlobalExceptionHandler에서 slack 메시지를 애너테이션을 이용해 aop 적용하여 메시징 코드만 따로 분리할 예정인데 하기 전에 예외핸들러 정리를 좀 해보려합니당!
=> refactor: 인증관련 서비스 예외 리팩토링
